### ISSUE TITLE
Build schemes from separate files

### ISSUE THREAD

**Issue by hepabolu** [jono-tt/edifact-lib#3]
I'm looking into separating segments into separate files so you won't have to include the same lines of json schema definition over and over again like UNB and UNT etc.

According to the [jsonschema lib](https://github.com/tdegrunt/jsonschema/blob/master/examples/ref.js) it should be possible to do something like this

in vermas.json.schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "interchangeHeader": {
      "edi_order": 1,
      "$ref": "/UNB",
      "required": true
    },
...
}
```

and e.g. in UNB.json.schema:

```
{
  "id": "/UNB",
  "type": "object",
  "properties": {
    "edi_tag": "UNB",
    ....
  }
}
```

and then 

```
var schema = JSON.parse(fs.readFileSync('vermas.json.schema', 'utf8');
var subSchema = JSON.parse(fs.readFileSync('UNB.json.schema', 'utf8');
....
validator.addSchema(subSchema, '/UNB');
```

I'm looking for the best location to implement this, because there currently is a nice separation between reading the files (in edi-to-json.js) and manipulating the schema (in edi-helpers.js). Adding the above would mean reading in additional schema files in the edi-helper.js

Is there a reason you have used only internal references (#/definitions) ?

**Comment by jdrew1303** [comment]
Hi @hepabolu 

I'd recommend using a third party library to handle the resolution of JSONSchema $refs and then pass the resolved schema into edifact-lib.

One of the libraries I use a lot is [json-schema-deref](https://www.npmjs.com/package/json-schema-deref). The core reason is it supports passing in custom resolvers (you can load from DBs, etc as well as URLs and files).

**Comment by hepabolu** [comment]
Hi @jdrew1303 Better late than never... Anyway, thanks for the suggestion. This totally fixed my problem. I've removed my changes about subschemas and simply build the schemas with a simple script.
